name: 🔍 PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, develop]

env:
  NODE_VERSION: "18"

jobs:
  # 🔍 Code Quality Checks
  code-quality:
    name: 🔍 Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📥 Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci --prefer-offline

      - name: 🔍 ESLint check
        run: npm run lint -- --max-warnings 0

      - name: 🎨 Prettier check
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,md,json}"

      - name: 🏗️ TypeScript check
        run: npx tsc --noEmit

      - name: 🧪 Run tests
        run: npm test -- --coverage --watchAll=false --passWithNoTests

      - name: 🏗️ Build check
        run: npm run build

  # 📊 Bundle Analysis
  bundle-analysis:
    name: 📊 Bundle Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8
    needs: code-quality

    steps:
      - name: 📥 Checkout PR
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci --prefer-offline

      - name: 🏗️ Build project
        run: npm run build

      - name: 📊 Analyze bundle size
        run: |
          echo "📊 Analyzing bundle size changes..."
          npx bundlesize
        continue-on-error: true

      - name: 📈 Generate bundle report
        run: |
          echo "📈 Generating detailed bundle analysis..."
          npx webpack-bundle-analyzer build/static/js/*.js --mode static --report build/bundle-report.html
        continue-on-error: true

      - name: 📤 Upload bundle report
        uses: actions/upload-artifact@v4
        with:
          name: bundle-report-${{ github.event.number }}
          path: build/bundle-report.html
          retention-days: 7

  # 🔒 Security Check
  security-check:
    name: 🔒 Security Check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 📥 Checkout PR
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci --prefer-offline

      - name: 🔍 Security audit
        run: |
          echo "🔍 Running security audit..."
          npm audit --audit-level moderate
        continue-on-error: true

      - name: 🔒 Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
        continue-on-error: true

  # 🧪 Visual Regression Testing
  visual-tests:
    name: 🧪 Visual Tests
    runs-on: ubuntu-latest
    timeout-minutes: 12
    needs: code-quality

    steps:
      - name: 📥 Checkout PR
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci --prefer-offline

      - name: 🏗️ Build project
        run: npm run build

      - name: 🚀 Start application
        run: |
          echo "🚀 Starting application for visual testing..."
          npx serve -s build -l 3000 &
          sleep 10
          curl -f http://localhost:3000 || exit 1

      - name: 📸 Take screenshots
        run: |
          echo "📸 Taking visual regression screenshots..."
          npx playwright install --with-deps
          npx playwright test --project=visual
        continue-on-error: true

  # 📝 PR Comment
  pr-comment:
    name: 📝 PR Comment
    runs-on: ubuntu-latest
    needs: [code-quality, bundle-analysis, security-check, visual-tests]
    if: always()

    steps:
      - name: 📝 Create PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('## 🔍 PR Validation Results')
            );

            const status = {
              'code-quality': '${{ needs.code-quality.result }}',
              'bundle-analysis': '${{ needs.bundle-analysis.result }}',
              'security-check': '${{ needs.security-check.result }}',
              'visual-tests': '${{ needs.visual-tests.result }}'
            };

            const getStatusIcon = (result) => {
              switch(result) {
                case 'success': return '✅';
                case 'failure': return '❌';
                case 'cancelled': return '⏹️';
                default: return '⏳';
              }
            };

            const comment = `## 🔍 PR Validation Results

            | Check | Status | Details |
            |-------|--------|---------|
            | 🔍 Code Quality | ${getStatusIcon(status['code-quality'])} | ESLint, Prettier, TypeScript, Tests |
            | 📊 Bundle Analysis | ${getStatusIcon(status['bundle-analysis'])} | Size analysis and optimization |
            | 🔒 Security Check | ${getStatusIcon(status['security-check'])} | Vulnerability scanning |
            | 🧪 Visual Tests | ${getStatusIcon(status['visual-tests'])} | Screenshot comparison |

            ### 📊 Overall Status
            ${Object.values(status).every(s => s === 'success') ? '✅ All checks passed!' : '⚠️ Some checks failed or are pending.'}

            <details>
            <summary>📋 Detailed Results</summary>

            - **Code Quality**: ${{ needs.code-quality.result }}
            - **Bundle Analysis**: ${{ needs.bundle-analysis.result }}
            - **Security Check**: ${{ needs.security-check.result }}
            - **Visual Tests**: ${{ needs.visual-tests.result }}

            </details>

            ---
            *This comment will be updated as checks complete.*`;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }
